apiVersion: skaffold/v2beta19
kind: Config
metadata:
    name: ticketing
deploy:
    kubectl:
        manifests:
            # - ./infra/k8s/*
            # - ./infra/k8s-dev/*
            #! run once only to install the client side load balancer
            # - ./infra/k8s/ingress-nginx-load-balancer-depl.yaml
            # init...
            - ./infra/k8s-dev/pod-schedule-priority-classes.yaml
            - ./infra/k8s-dev/ingress-srv.yaml
            # - dashboard-adminuser.yaml
            # first-priority
            - ./infra/k8s/nats-depl.yaml
            # second-priority
            - ./infra/k8s/auth-depl.yaml
            - ./infra/k8s/auth-mongo-depl.yaml
            # # third-priority
            - ./infra/k8s/expiration-depl.yaml
            - ./infra/k8s/expiration-redis-depl.yaml
            # # fourth-priority
            - ./infra/k8s/payments-depl.yaml
            - ./infra/k8s/payments-mongo-depl.yaml
            # # fifth-priority
            - ./infra/k8s/tickets-depl.yaml
            - ./infra/k8s/tickets-mongo-depl.yaml
            # # medium-priority-nonpreempting
            - ./infra/k8s/client-depl.yaml
            # # low-priority-nonpreempting
            - ./infra/k8s/orders-depl.yaml
            - ./infra/k8s/orders-mongo-depl.yaml
build:
    local:
        push: false
    artifacts:
        - image: superclass2016/auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: superclass2016/client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '**/*.js'
                    dest: .
        - image: superclass2016/expiration
          context: expiration
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: superclass2016/orders
          context: orders
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: superclass2016/payments
          context: payments
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: superclass2016/tickets
          context: tickets
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
