apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - name: auth
                  image: superclass2016/auth
                  env:
                      - name: MONGO_URI
                        value: 'mongodb://auth-mongo-srv:27017/auth'
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret
                                key: JWT_KEY
                  resources:
                      requests:
                          cpu: '150m'
                          memory: '150Mi'
                      limits:
                          cpu: '250m'
                          memory: '250Mi'
            priorityClassName: second-priority
            tolerations:
                - key: ''
                  operator: 'Exists'
                  effect: 'NoExecute'
                  tolerationSeconds: 120
---
apiVersion: v1
kind: Service
metadata:
    name: auth-srv
spec:
    selector:
        app: auth
    ports:
        - name: auth
          protocol: TCP
          port: 3000
          targetPort: 3000
